-- Set command options for Db2 CLP to remove output to sysout
UPDATE COMMAND OPTIONS USING DisplayOutput OFF
UPDATE COMMAND OPTIONS USING StripHeaders ON
-- Connect to the Db2 instance
CONNECT TO 204.90.115.200:5040/DALLASC
-- Set encryption password
SET ENCRYPTION PASSWORD = '?PASS?'
-- Pull corresponding data
SELECT P.PCODE, M.MCODE, L.PQUANTITY, M.MNAME, M.MVALID, P.PNAME \
    FROM ?SCHEMA?.STKPART P, ?SCHEMA?.STKMAN M, ?SCHEMA?.STKLVL L, ?SCHEMA?.STKAVAIL A \
    WHERE P.PID = L.PID AND P.MID = M.MID AND P.MID = A.MID AND P.PNAME LIKE '%?KEY?%' AND DECRYPT_CHAR(A.MAVAILABLE) LIKE 'YES' \
    ORDER BY P.PCODE
-- Stop Db2 CLP
TERMINATE
